*---------------------------------------------------------------------*
*    view related data declarations
*---------------------------------------------------------------------*
*...processing: ZVI_SET_DESCRIPT................................*
TABLES: ZVI_SET_DESCRIPT, *ZVI_SET_DESCRIPT. "view work areas
CONTROLS: TCTRL_ZVI_SET_DESCRIPT
TYPE TABLEVIEW USING SCREEN '0003'.
DATA: BEGIN OF STATUS_ZVI_SET_DESCRIPT. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZVI_SET_DESCRIPT.
* Table for entries selected to show on screen
DATA: BEGIN OF ZVI_SET_DESCRIPT_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZVI_SET_DESCRIPT.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZVI_SET_DESCRIPT_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZVI_SET_DESCRIPT_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZVI_SET_DESCRIPT.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZVI_SET_DESCRIPT_TOTAL.

*...processing: ZVI_SET_PROJECT.................................*
TABLES: ZVI_SET_PROJECT, *ZVI_SET_PROJECT. "view work areas
CONTROLS: TCTRL_ZVI_SET_PROJECT
TYPE TABLEVIEW USING SCREEN '0001'.
DATA: BEGIN OF STATUS_ZVI_SET_PROJECT. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZVI_SET_PROJECT.
* Table for entries selected to show on screen
DATA: BEGIN OF ZVI_SET_PROJECT_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZVI_SET_PROJECT.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZVI_SET_PROJECT_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZVI_SET_PROJECT_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZVI_SET_PROJECT.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZVI_SET_PROJECT_TOTAL.

*...processing: ZVI_SET_VARIABLE................................*
TABLES: ZVI_SET_VARIABLE, *ZVI_SET_VARIABLE. "view work areas
CONTROLS: TCTRL_ZVI_SET_VARIABLE
TYPE TABLEVIEW USING SCREEN '0002'.
DATA: BEGIN OF STATUS_ZVI_SET_VARIABLE. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZVI_SET_VARIABLE.
* Table for entries selected to show on screen
DATA: BEGIN OF ZVI_SET_VARIABLE_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZVI_SET_VARIABLE.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZVI_SET_VARIABLE_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZVI_SET_VARIABLE_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZVI_SET_VARIABLE.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZVI_SET_VARIABLE_TOTAL.

*.........table declarations:.................................*
TABLES: ZTB_SET_DESCRIPT               .
TABLES: ZTB_SET_PROJECT                .
TABLES: ZTB_SET_VARIABLE               .
